1\. Enter the name of the exported Wrike file below. 
> Do not include file extensions.
> Leave the '' in place.

In [5]:
filename = 'ENTER_NAME_OF_FILE'

2\. Run the below block of code and copy the output to be pasted.

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline
file = filename+'.xls'
df = pd.read_excel(file)
newdf = df.ix[:,['Folder','Parent task','Status']]
newdf['Folder'] = newdf['Folder'].map(lambda x: x.lstrip('/').rstrip('/'))
newdf = newdf.dropna()
aggregations = {
    'Status':{
        'Status Count': 'count',
    },
}
def addTotals(row):
    if row['Status', ''] == 'Completed':
        tempdf = totals.loc[totals['Folder'] == row[0]]
        tempdf = tempdf.ix[:,1]
        return tempdf.iloc[0]
    else:
        return ''
totals = newdf.groupby(['Folder']).count()
totals.reset_index(inplace=True)
grouped = newdf.groupby(['Folder', 'Status']).agg(aggregations)
grouped.reset_index(inplace=True)
grouped['Total Tasks'] = grouped.apply(addTotals,axis=1)
grouped.rename(columns={('Folder', ''):('Site', '')}, inplace=True)
def percent(row):
    if row[('Total Tasks', '')] != '':
        return (row['Status','Status Count']/row['Total Tasks','']*100).round(2).astype(str) + '%'
    else:
        return ''
grouped['Completion %'] = grouped.apply(percent,axis=1)
totalTaskCount = grouped['Status', 'Status Count'].sum()
completedTaskCount = 0
for x in range(grouped.shape[0]):
    if grouped.get_value(x,('Status','')) == 'Completed':
        completedTaskCount += grouped.get_value(x,('Status','Status Count'))
totalPercentComplete = ((completedTaskCount/totalTaskCount)*100).round(2).astype(str)+'%'
grouped.loc[grouped.shape[0]]=['Completed / Total','',completedTaskCount,totalTaskCount,totalPercentComplete]
grouped

          Folder     Status              Total Tasks Completion %
                            Status Count
0         Angola     Active            3
1         Angola  Cancelled            1
2         Angola  Completed           14          18       77.78%
3         Celaya     Active            2
4         Celaya  Cancelled            1
5         Celaya  Completed           16          19       84.21%
6   Harrisonburg     Active            1
7   Harrisonburg  Cancelled            1
8   Harrisonburg  Completed           18          20        90.0%
9       Hartwell  Cancelled            1
10      Hartwell  Completed           16          17       94.12%
11     Kettering  Cancelled            1
12     Kettering  Completed           16          17       94.12%
13      Napoleon     Active           10
14      Napoleon  Completed           14          24       58.33%
15    Owen Sound     Active            6
16    Owen Sound  Completed           17          23       73.91%
17     Paragould  Cancelled            1
18     Paragould  Completed           20          21       95.24%
19       Reynosa     Active            5
20       Reynosa  Cancelled            1
21       Reynosa  Completed           15          21       71.43%
22       Totals:                     146         180       81.11%

3\. Run the next line if you need the above information as a csv.
> Note: If you are running this for multiple documents, you must move or rename the output .csv file or it will be overwritten.

In [ ]:
grouped.to_csv('out.csv')